# Generated by Django 4.2 on 2023-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_app', '0002_customer_order_volcano_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volcano',
            name='Country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='Latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='Longitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='Volcano_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='Volcano_Type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='epoch_period',
            field=models.CharField(max_length=100),
        ),
    ]