# Generated by Django 4.1.2 on 2023-04-30 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_app', '0003_alter_volcano_country_alter_volcano_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volcano',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
