# Generated by Django 4.2 on 2023-04-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_app', '0004_volcano_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volcano',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='volcano',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]