# Generated by Django 4.2.1 on 2023-05-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_app', '0006_remove_order_customer_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('Volcano_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('Volcano_Name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('add_to_cart', models.BooleanField(default=False)),
                ('Volcano_Image', models.URLField(max_length=100)),
            ],
        ),
    ]
