# Generated by Django 4.2.1 on 2023-05-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_app', '0008_remove_cart_volcano_id_cart_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
