# Generated by Django 4.2.1 on 2023-05-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_app', '0011_rename_product_cartitem_volcano_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='id',
            new_name='cart_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='add_to_cart',
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
