# Generated by Django 4.2.1 on 2023-05-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_app', '0012_rename_id_cart_cart_id_remove_cart_add_to_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.AutoField(default=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.IntegerField(unique=True),
        ),
    ]
