# Generated by Django 4.2.1 on 2023-05-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_app', '0015_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
